### PR TITLE
select path separator at compile time

### PR DESCRIPTION
**Pull request by marcellussiegburg**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
This doesn't work. The value of `System.FilePath.Posix.searchPathSeparator` on my system is `':'`.

**Comment by jvoigtlaender** [comment]
Shouldn't you use `System.FilePath.searchPathSeparator` instead?

**Comment by marcellussiegburg** [comment]
Yes I guess so, but in that case the haddock
http://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html#v:searchPathSeparator
is misleading.

**Comment by jvoigtlaender** [comment]
Though, at the top of that page ...

**Comment by marcellussiegburg** [comment]
Can you try this on Windows?

**Comment by jvoigtlaender** [comment]
Works

**Pull request merged**
