### PR TITLE
Set scope for FName

### PR DESCRIPTION
**Pull request by marcellussiegburg**
Occasionally, Alloy fails with an error message, that an scope for FName is missing.
```Java
You must specify a scope for sig "this/FName"
	at edu.mit.csail.sdg.translator.ScopeComputer.derive_overall_scope(ScopeComputer.java:256)
	at edu.mit.csail.sdg.translator.ScopeComputer.<init>(ScopeComputer.java:401)
	at edu.mit.csail.sdg.translator.ScopeComputer.compute(ScopeComputer.java:469)
	at edu.mit.csail.sdg.translator.TranslateAlloyToKodkod.<init>(TranslateAlloyToKodkod.java:148)
	at edu.mit.csail.sdg.translator.TranslateAlloyToKodkod.execute_command(TranslateAlloyToKodkod.java:535)
	at alloy.RunAlloy.main(RunAlloy.java:39)
```

### CODE REVIEW

**Comment by marcellussiegburg** [comment]
The error occurs for instance for this file
```Alloy
// Alloy Model for CD2
// Produced by Haskell reimplementation of Eclipse plugin transformation
// Generated:

module umlp2alloy/CD2Module

///////////////////////////////////////////////////
// Generic Head of CD Model - adapted/simplified
///////////////////////////////////////////////////

//Names of fields/associations in classes of the model
abstract sig FName {}

//Parent of all classes relating fields and values
abstract sig Obj {
  get : FName -> set Obj
}

pred ObjFNames[objs : set Obj, fNames : set FName] {
  no objs.get[FName - fNames]
}

pred ObjLUAttrib[objs : set Obj, fName : FName, fType : set Obj, low, up : Int] {
  ObjLAttrib[objs, fName, fType, low]
  all o : objs | #o.get[fName] =< up
}

pred ObjLAttrib[objs : set Obj, fName : FName, fType : set Obj, low : Int] {
  objs.get[fName] in fType
  all o : objs | #o.get[fName] >= low
}

pred ObjLU[objs : set Obj, fName : FName, fType : set Obj, low, up : Int] {
  ObjL[objs, fName, fType, low]
  ObjU[objs, fName, fType, up]
}

pred ObjL[objs : set Obj, fName : FName, fType : set Obj, low : Int] {
  all r : objs | #{l : fType | r in l.get[fName]} >= low
}

pred ObjU[objs : set Obj, fName : FName, fType : set Obj, up : Int] {
  all r : objs | #{l : fType | r in l.get[fName]} =< up
}

pred Composition[left : set Obj, lFName : set FName, right : set Obj] {
  // all l1, l2 : left | (#{l1.get[lFName] & l2.get[lFName]} > 0) => l1 = l2
  all r : right | #{l : left, lF : lFName | r in l.get[lF]} =< 1
}

fact NonEmptyInstancesOnly {
  some Obj
}

fact LimitIsolatedObjects {
  #Obj >= mul[2, #{o : Obj | no o.get and no get.o}]
}

///////////////////////////////////////////////////
// Structures potentially common to multiple CDs
///////////////////////////////////////////////////

// Concrete names of fields

// Classes
sig A extends Obj {}
sig B extends Obj {}
sig C extends Obj {}
sig D extends Obj {}

///////////////////////////////////////////////////
// CD2
///////////////////////////////////////////////////

// Types wrapping subtypes
fun ASubsCD2 : set Obj {
  A
}
fun BSubsCD2 : set Obj {
  B + ASubsCD2
}
fun CSubsCD2 : set Obj {
  C + BSubsCD2 + DSubsCD2
}
fun DSubsCD2 : set Obj {
  D
}

// Types wrapping field names
fun AFieldNamesCD2 : set FName {
  BFieldNamesCD2
}
fun BFieldNamesCD2 : set FName {
  CFieldNamesCD2
}
fun CFieldNamesCD2 : set FName {
  none
}
fun DFieldNamesCD2 : set FName {
  CFieldNamesCD2
}

// Types wrapping composite structures and field names
fun ACompositesCD2 : set Obj {
  BCompositesCD2
}
fun ACompFieldNamesCD2 : set FName {
  BCompFieldNamesCD2
}
fun BCompositesCD2 : set Obj {
  CCompositesCD2
}
fun BCompFieldNamesCD2 : set FName {
  CCompFieldNamesCD2
}
fun CCompositesCD2 : set Obj {
  none
}
fun CCompFieldNamesCD2 : set FName {
  none
}
fun DCompositesCD2 : set Obj {
  CCompositesCD2
}
fun DCompFieldNamesCD2 : set FName {
  CCompFieldNamesCD2
}

// Properties
pred cd2 {

  Obj = A + B + C + D

  // Contents
  ObjFNames[A, AFieldNamesCD2]
  ObjFNames[B, BFieldNamesCD2]
  ObjFNames[C, CFieldNamesCD2]
  ObjFNames[D, DFieldNamesCD2]

  // Associations

  // Compositions
  Composition[ACompositesCD2, ACompFieldNamesCD2, A]
  Composition[BCompositesCD2, BCompFieldNamesCD2, B]
  Composition[CCompositesCD2, CCompFieldNamesCD2, C]
  Composition[DCompositesCD2, DCompFieldNamesCD2, D]

}

///////////////////////////////////////////////////
// CD3
///////////////////////////////////////////////////

// Types wrapping subtypes
fun ASubsCD3 : set Obj {
  A
}
fun BSubsCD3 : set Obj {
  B + ASubsCD3
}
fun CSubsCD3 : set Obj {
  C + BSubsCD3 + DSubsCD3
}
fun DSubsCD3 : set Obj {
  D
}

// Types wrapping field names
fun AFieldNamesCD3 : set FName {
  BFieldNamesCD3
}
fun BFieldNamesCD3 : set FName {
  CFieldNamesCD3
}
fun CFieldNamesCD3 : set FName {
  none
}
fun DFieldNamesCD3 : set FName {
  CFieldNamesCD3
}

// Types wrapping composite structures and field names
fun ACompositesCD3 : set Obj {
  BCompositesCD3
}
fun ACompFieldNamesCD3 : set FName {
  BCompFieldNamesCD3
}
fun BCompositesCD3 : set Obj {
  CCompositesCD3
}
fun BCompFieldNamesCD3 : set FName {
  CCompFieldNamesCD3
}
fun CCompositesCD3 : set Obj {
  none
}
fun CCompFieldNamesCD3 : set FName {
  none
}
fun DCompositesCD3 : set Obj {
  CCompositesCD3
}
fun DCompFieldNamesCD3 : set FName {
  CCompFieldNamesCD3
}

// Properties
pred cd3 {

  Obj = A + B + C + D

  // Contents
  ObjFNames[A, AFieldNamesCD3]
  ObjFNames[B, BFieldNamesCD3]
  ObjFNames[C, CFieldNamesCD3]
  ObjFNames[D, DFieldNamesCD3]

  // Associations

  // Compositions
  Composition[ACompositesCD3, ACompFieldNamesCD3, A]
  Composition[BCompositesCD3, BCompFieldNamesCD3, B]
  Composition[CCompositesCD3, CCompFieldNamesCD3, C]
  Composition[DCompositesCD3, DCompFieldNamesCD3, D]

}

///////////////////////////////////////////////////
// Run commands
///////////////////////////////////////////////////

run { cd2 and (not cd3) } for 5 Obj, 5 Int
```

**Comment by jvoigtlaender** [comment]
The issue is, I guess: 

There is not a single `sig` declaration for `FName` here. And since there is also no scope given for `FName` in the `run` command, Alloy does not know how to set the scope.

Steps suggested for diagnosis:

Is it the case that this happens only when there are associations, aggregations, compositions in the class diagram(s) at all?

Does it also happen (in cases as above) if the `run` command is as previously, with just a `for 5` scope, which then also covers `FName`?

**Comment by jvoigtlaender** [comment]
... when there are *no* ...

**Comment by marcellussiegburg** [comment]
Executing it with `for 5` scope resolves the issue

**Comment by jvoigtlaender** [comment]
So it would also be resolved by adding an explicit scope for `FName`. That could be obtained from the number of field names, though it is a bit silly since in all cases except when there are no field names at all, Alloy would deduce the scope automatically from the number of `one sig` declarations. (And adding an explicit scope declaration nevertheless is only a possible source for error.)

So maybe simply never call Alloy with a scenario of no field names at all? (Which makes sense, since there are no interesting object diagrams if there are no field names.)

**Comment by marcellussiegburg** [comment]
It might be that this happens only, if there no edges at all (at least that triggers the problem always)

**Comment by jvoigtlaender** [comment]
Where "edges" means "associations, aggregations, compositions"?

**Comment by marcellussiegburg** [comment]
Yes, `Assoc`s.

**Comment by marcellussiegburg** [comment]
I guess preventing the call in this case is a feasible solution.

**Comment by jvoigtlaender** [comment]
Then I declare the solution: Discard class diagrams that have no `Assoc`s.

**Comment by jvoigtlaender** [comment]
Or actually, in our specific exercise task setup, discard cases where neither `cd2` nor `cd3` has an `Assoc`.

**Pull request merged**
